# Generated by Django 3.2.7 on 2021-11-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_alunos_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='deleted',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='cpf',
            field=models.CharField(db_index=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='deleted',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='nome',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
