# Generated by Django 3.2.7 on 2021-09-18 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oficinas', '0001_initial'),
        ('chamada', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamada',
            name='oficina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oficinas.oficinas'),
        ),
    ]
