# Generated by Django 3.2.7 on 2021-09-18 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamada', '0002_chamada_oficina'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamadaaluno',
            name='presente',
            field=models.BooleanField(default=True),
        ),
    ]
