# Generated by Django 3.2.7 on 2021-11-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamada', '0003_chamadaaluno_presente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamada',
            name='deleted',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='chamadaaluno',
            name='deleted',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='chamadaaluno',
            name='presente',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
