# Generated by Django 3.2.7 on 2021-09-18 00:20

from django.db import migrations, models
import django.db.models.deletion
import functools
import oficinas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0002_alunos_user'),
        ('orientador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oficinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('local', models.CharField(blank=True, max_length=200, null=True)),
                ('link', models.CharField(blank=True, max_length=300, null=True)),
                ('horario', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.IntegerField(default=0)),
                ('orientador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orientador.orientador')),
            ],
        ),
        migrations.CreateModel(
            name='OficinaImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to=functools.partial(oficinas.models.random_image_name, *('media',), **{}))),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.IntegerField(default=0)),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oficinas.oficinas')),
            ],
        ),
        migrations.CreateModel(
            name='OficinaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.IntegerField(default=0)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.alunos')),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oficinas.oficinas')),
            ],
        ),
    ]
