# Generated by Django 3.2.7 on 2021-10-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orientador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orientador',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
